# 首先更改这些
owner: lmq8267 # 您的 GitHub 用户名
repo: uptime # 此存储库的名称

sites:
  - name: VNT-TCP-UDP
    check: tcp-ping
    url: vnt.wherewego.top
    port: 29872
  - name: VNT服务器 TCP-UDP
    check: tcp-ping
    url: s4.serv00.com
    port: 29872
  - name: VNT服务器 TCP-UDP
    check: tcp-ping
    url: s1.ct8.pl
    port: 29872
  - name: VNT服务器 WS
    check: tcp-ping
    url: vnt.us.kg
    port: 80
  - name: EasyTier官方服务器 TCP-UDP
    check: tcp-ping
    url: public.easytier.top
    port: 11010
  - name: 1hc.us.kg
    url: http://1hc.us.kg
  - name: 短链接s4.serv00.com
    url: http://s4.serv00.com:8828

status-website:
  # 添加您的自定义域名，如果没有域名，请删除 `cname` 行
  # 如果没有自定义域名，请取消注释 `baseUrl` 行并在其中添加您的仓库名称
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 服务状态
  introTitle: "公共节点仅用于测试，对于生产，请设置您自己的节点。"
  introMessage: 
  navbar:
    - title: 状态
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  i18n:
    url: "URL"
    status: "状态"
    history: "历史"
    responseTime: "响应时间"
    uptime: "正常运行时间"
    up: "正常✅"
    degraded: "不佳⚠️"
    down: "离线❌"
    responseTimeGraphAlt: "响应时间图"
    ms: "毫秒"
    liveStatus: "实时状态"
    liveStatusHtmlComment: "<!--实时状态-->"
    allSystemsOperational: "所有服务运行正常✅"
    degradedPerformance: "服务状态不佳⚠️"
    completeOutage: "所有服务全部离线❌"
    partialOutage: "部分服务故障⚠️"

    activeIncidents: 当前事件
    incidentReport: "事件 #$NUMBER 报告 →"
    activeIncidentSummary: 于 $DATE 开始，包含 $POSTS 条帖子
    incidentTitle: 事件 $NUMBER 详情
    incidentDetails: 事件详情
    incidentFixed: 已修复
    incidentOngoing: 正在进行
    incidentOpenedAt: 开始时间
    incidentClosedAt: 结束时间
    incidentViewOnGitHub: 在 GitHub 上查看并订阅
    incidentCommentSummary: $DATE 由 $AUTHOR 发布
    incidentBack: ← 返回所有事件
    pastIncidents: 历史事件
    pastIncidentsResolved: 在 $MINUTES 分钟内解决，包含 $POSTS 条帖子
    liveStatus: 实时状态
    overallUptime: "总体正常运行时间：$UPTIME"
    overallUptimeTitle: 总体正常运行时间
    averageResponseTime: "平均响应时间：$TIME 毫秒"
    averageResponseTimeTitle: 平均响应时间
    sevelDayResponseTime: 7 天响应时间
    responseTimeMs: 响应时间（毫秒）
    up: 正常
    down: 离线
    degraded: 状态不佳
    ms: 毫秒
    loading: 加载中
    navGitHub: GitHub
    footer: 本页面是 [开源项目]($REPO)，由 [Upptime](https://upptime.js.org) 提供支持
    rateLimitExceededTitle: 超过速率限制
    rateLimitExceededIntro: 您已超过每小时请求次数限制，因此需要等待才能再次访问此网站。或者，您可以添加 GitHub 个人访问令牌以继续使用本网站。
    rateLimitExceededWhatDoesErrorMean: 这个错误是什么意思？
    rateLimitExceededErrorMeaning: 本网站使用 GitHub API 获取网站状态的实时数据。默认情况下，GitHub 每小时允许每个 IP 地址 60 次请求，而您已经用完了。
    rateLimitExceededErrorHowCanFix: 如何解决？
    rateLimitExceededErrorFix: 您可以等待一小时，IP 地址的限制将被恢复。或者，您可以添加 GitHub 个人访问令牌，每小时额外获得 5000 次请求。
    rateLimitExceededGeneratePAT: 了解如何生成个人访问令牌
    rateLimitExceededHasSet: 您已设置个人访问令牌。
    rateLimitExceededRemoveToken: 删除令牌
    rateLimitExceededGitHubPAT: GitHub 个人访问令牌
    rateLimitExceededCopyPastePAT: 复制并粘贴您的令牌
    rateLimitExceededSaveToken: 保存令牌
    errorTitle: 发生错误
    errorIntro: 尝试获取最新状态详情时发生错误。
    errorText: 您可以稍后再试。
    errorHome: 返回主页
    pastScheduledMaintenance: 历史计划维护
    scheduledMaintenance: 计划维护
    scheduledMaintenanceSummaryStarted: 于 $DATE 开始，持续 $DURATION 分钟
    scheduledMaintenanceSummaryStarts: 将于 $DATE 开始，预计持续 $DURATION 分钟
    startedAt: 开始时间
    startsAt: 计划开始时间
    duration: 持续时间
    durationMin: $DURATION 分钟
    incidentCompleted: 已完成
    incidentScheduled: 已计划
    duration24H: 24 小时
    duration7D: 7 天
    duration30D: 30 天
    duration1Y: 1 年
    durationAll: 全部
    #locale: zh-CN
    locale: en-US


# Upptime 还支持通知、分配问题等功能
# 请参阅 https://upptime.js.org/docs/configuration
